# Generated by Django 3.0.6 on 2020-06-03 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('cellphone', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
