# Generated by Django 3.0.6 on 2020-06-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200603_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': '사용자'},
        ),
    ]
