# Generated by Django 3.0.6 on 2020-06-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200603_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/<django.db.models.fields.EmailField>'),
        ),
    ]
