# Generated by Django 3.0.6 on 2020-06-03 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20200603_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('contents', models.IntegerField(default=0)),
                ('classification', models.CharField(max_length=10)),
                ('product_image', models.ImageField(blank=True, default='media/base.jpg', upload_to='media/')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Users')),
            ],
            options={
                'verbose_name_plural': '상품',
            },
        ),
    ]
