# Generated by Django 3.0.6 on 2020-06-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200603_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='contents',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='title',
            new_name='product',
        ),
    ]
