# Generated by Django 3.0.6 on 2020-06-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200603_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='classification',
            field=models.CharField(choices=[('SP', 'Spring'), ('SU', 'Summer'), ('FA', 'Fall'), ('WI', 'Winter')], max_length=2),
        ),
    ]
