# Generated by Django 3.0.6 on 2020-06-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200603_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='classification',
            field=models.CharField(choices=[('SP', '봄'), ('SU', '여름'), ('FA', '가을'), ('WI', '겨울')], max_length=2),
        ),
    ]
