# Generated by Django 3.0.6 on 2020-06-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200603_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='post/'),
        ),
    ]
